# .github/workflows/deploy.yml

name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main # Change this if your default branch is different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Specify the Node.js version your project uses

      # 3. Install Dependencies
      - name: Install Dependencies
        run: |
          cd KV6002
          npm install

      # 4. Build the React App
      - name: Build Project
        run: |
          cd KV6002
          npm run build

      # 5. Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # 6. Deploy to Firebase Hosting
      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          cd KV6002
          firebase deploy --only hosting --token "${FIREBASE_TOKEN}"
