name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Ensure this matches your project's Node.js version

      - name: Install Dependencies
        run: |
          cd KV6002
          npm install

      - name: Build Project
        run: |
          cd KV6002
          npm run build

      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          cd KV6002
          firebase deploy --only hosting
